name: Butler Imagery
favicon: null
layout_spectrum: 0.4042332915123552
typography_spectrum: 0.19664693414233625
title: Butler Imagery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#919191'
    - '#2f2f2f'
    - '#d6d6d6'
  brandStrength: 0.5306705073453486
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
